---
- name: Installation
  hosts: all
  tasks:
  - name: Install httpd packages
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "RedHat"
  - name: Install apache2 packages
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"
